securesign/rekor

- OWNERS
Needed by the OpenShift prow jobs. This enables actions through commands such as /lgtm and /approve.
> chore: add OWNERS file for OpenShift CI / Prow

- redhat/patches/0001-dockerfile.patch
Still working on the automation for this. The patch doesn't apply right now as upstream changed the base image. It might be better in the long run to do something different than a patch file if the base image tag changes very frequently.
> chore: update patch file

- redhat/patches/0001-dockerfile.patch
- redhat/release/update-to-head.sh
If provided the update-to-head.sh script will now accept an upstream git-ref (typically a release tag, e.g. 1.2.2). If a git-ref is provided, there MUST be a corresponding branch in securesign/rekor with the same name, prefixed with "midstream-", e.g. "midstream-v1.2.2". The script also pushes to a `redhat-<git-ref>` branch if a git-ref was provided.
This allows us to maintain branch history in midstream, corresponding to upstream releases, and typically pins the upstream Dockerfile sha.
I have also recently pushed a [`midstream-v1.2.2`](https://github.com/securesign/rekor/tree/midstream-v1.2.2) branch to test this against once this PR lands. As [you can see](https://github.com/securesign/rekor/compare/main...securesign:rekor:midstream-v1.2.2) the branch maintains the specific updates …
> chore: modify sync script to update based on git-ref

- README.md
- redhat/release/update-to-head.sh
In https://github.com/securesign/rekor/commit/b5f82dfbf11a19e4526c414d169beb45deb92790 there were some improvements to how we can handle versions in CI. However, I don't think those changes were really enough. In that commit, I conflated the `release-next` branch with "whatever we happened to be building". But really I think it's better to use separate branches all around.
With this commit, the update script now does the following.
- If no arguments are supplied, it uses the `release-next` and `release-next-ci` branches to synchronize the absolute latest from upstream to our `release-next` branch. This is exactly what we started with.
- If a git-ref is supplied, it creates or force pushes a `redhat-${git-ref}` branch which is our midstream version of upstream at `${git-ref}` (patches …
> chore: better handling of versioned branches

- redhat/overlays/rekor-cli/Dockerfile.cli
This pr is related to this issue [here](https://github.com/securesign/rekor/issues/14), it involves creating a dockerfile for the rekor-cli binary.
1.  Place the Dockerfile in the root directory of https://github.com/securesign/rekor/tree/release-next, or https://github.com/securesign/rekor/tree/redhat-v1.2.2
2. Build the dockerfile using this cmd `podman build . -t quay.io/<repo_name>/rekor-cli:v1.2.2 -f Dockerfile.cli`
3. Once built you should be able to access the rekor cli like so `podman run quay.io/<repo_name>/rekor-cli:v1.2.2 <rekor-cli-command>`
> add dockerfile for rekor-cli

- .github/workflows/cronjobs.yaml
The github workflow that runs this script to update HEAD was using a git URL for the remote. That was causing failures in the action since there's no auth from there. Just using HTTP should resolve the issue.
> chore: modify update script to not send auth

- .tekton/rekor-server-pull-request.yaml
- .tekton/rekor-server-push.yaml
I think my wires got crossed when I first attempted to onboard multiple components in a single repo. The name of the pipelines was mixed up with the name of the files. Anyhooo... I believe this should fix it.
> chore: update tekton pipelines with correct naming

- redhat/overlays/Dockerfile.backfill-redis
- redhat/patches/0002-makefile.patch
This commit adds a Dockerfile for building a `backfill-redis` image, which should be used periodically to ensure that redis contains the complete rekor log.
The patchfile is required due to this upstream issue:
https://github.com/sigstore/rekor/pull/1685
Once that pull request has been merged, we'll need to remove the patchfile from `main` but not from the `midstream-v1.2.2` branch unless it is backported upstream.
/cherry-pick midstream-v1.2.2
> feat: add Dockerfile for backfill-redis

- redhat/patches/0001-dockerfile.patch
The upstream docker file was updated over the weekend and since there was already a pr open for an older patch GitHub actions never picked it up
> update patch file

- redhat/overlays/Dockerfile
- redhat/overlays/Dockerfile.backfill-redis
- redhat/overlays/Dockerfile.cli
This pr is related to this issue https://issues.redhat.com/browse/SECURESIGN-115, and involves adding an extra label to the Dockerfiles for Comet.
> SECURESIGN-115 | Add new label to dockerfiles for Comet

- redhat/overlays/Dockerfile
- redhat/overlays/Dockerfile.backfill-redis
- redhat/overlays/Dockerfile.cli
Updates to repoisitory tag 1.19.13-4.1697647145
> chore: update SHAs to the latest for UBI9 go-toolset

- redhat/overlays/Dockerfile
- redhat/overlays/Dockerfile.backfill-redis
- redhat/overlays/Dockerfile.cli
Small pr to update the base images of some stages that don't require go-tools
/cherrypick midstream-v1.2.2
> chore: Change base image of Dockerfiles

- .github/workflows/cronjobs.yaml
Pr to add the check-image-version action to the scaffolding repo. Example prs : https://github.com/JasonPowr/rekor/pull/66, https://github.com/JasonPowr/rekor/pull/65
Before merged settings need to be changed.
1. Actions need to be able to create pull requests (settings -> Actions -> General -> Workflow permissions)
2. Actions need read and write permissions (settings -> Actions -> General -> Workflow permissions)
> feat: Add reusable check-image-version job

- .tekton/backfill-redis-pull-request.yaml
- .tekton/backfill-redis-push.yaml
- .tekton/rekor-cli-pull-request.yaml
- .tekton/rekor-cli-push.yaml
- .tekton/rekor-server-pull-request.yaml
- .tekton/rekor-server-push.yaml
As of today, RHTAP does not allow unknown task images to run, causing a failure in the pipeline. We need to remove these tests temporarily until the RHTAP team can provide a way to support these.
Related Jira: https://issues.redhat.com/browse/EC-20
> chore: remove unit and e2e tests from the pipeline

- redhat/overlays/Dockerfile.cli
The cachi2 pipelinerun task in RHTAP modifies the Dockerfile to inject the cached dependency information into the build. This causes the git version - which is injected into the CLI version output - to include a `-dirty` suffix.
The modification in this commit stashes those changes, and then gets the git hash, storing it in the `GIT_VERSION` environment variable, then pops those changes back off of the stash and runs the build as before.
The commit also contains some optimizations so that most of the `RUN` commands are consolidated into one.
> rhtap: update Dockerfile to get a clean git hash

- .tekton/backfill-redis-pull-request.yaml
- .tekton/backfill-redis-push.yaml
- .tekton/rekor-cli-pull-request.yaml
- .tekton/rekor-cli-push.yaml
- .tekton/rekor-server-pull-request.yaml
- .tekton/rekor-server-push.yaml
FOSS legally requires distribution of source. Adding this task should generate an image that we can distribute automagically.
> pipelines: add source image build

- .tekton/rekor-e2e-test.yaml
- docker-compose.yml
Related to same issue behind https://github.com/securesign/scaffolding/pull/125 and depends on it.
Dependency of certified helm charts (only use certified images check). If the implementation strategy gets approved by lance, then we will swap out the image that gets build from RHTAP once [scaffolding #125]( https://github.com/securesign/scaffolding/pull/125) gets merged. Because of that ...
/hold
> removing args on rhel9/redis-6 image

- Build.mak
- Dockerfile
- Dockerfile.backfill-redis
- Dockerfile.cli
- cmd/rekor-server/e2e_test.go
- e2e-test.sh
Since we are foregoing the use of update-to-head.sh for this next release, these overlays only need to be applied once, when the branch is created.
> chore: copy overlays from midstream-v1.2.2

- Dockerfile
- Dockerfile.backfill-redis
- Dockerfile.cli
Similar to: https://github.com/securesign/scaffolding/pull/132 but for rekor.
Fixes build issues based on go version in the base image.
/cc @lance
> chore: bump go version of base image to 1.21

- .dockerignore
Having the Makefile.swagger get copied into the image was causing the build to hang so ive added a docker ignore as the file is regenerated anyways.
> [SECURESIGN-247] Adding necessary files for build and RHTAP Onboarding

- Dockerfile.cli
There was an extra go.mod file in hacks/tools that I missed on the config that was causing swagger make targets to fail.
> Updating Dockerfile with extra go mod vendor.

- .dockerignore
- .tekton/backfill-redis-1-0-gamma-pull-request.yaml
- .tekton/backfill-redis-1-0-gamma-push.yaml
- .tekton/rekor-server-1-0-gamma-pull-request.yaml
- .tekton/rekor-server-1-0-gamma-push.yaml
- Dockerfile
- Dockerfile.backfill-redis
- Dockerfile.cli
Also includes changes to get rekor back on a stable build in RHTAP
> enable hermetic builds and prefetched dependencies

- .tekton/backfill-redis-1-0-gamma-pull-request.yaml
- .tekton/backfill-redis-1-0-gamma-push.yaml
- .tekton/rekor-cli-1-3-pull-request.yaml
- .tekton/rekor-cli-1-3-push.yaml
- .tekton/rekor-server-1-0-gamma-pull-request.yaml
- .tekton/rekor-server-1-0-gamma-push.yaml
- .tekton/rekor-unit-test.yaml
- pkg/api/entries.go
PR to re-add go unit tests to rekor
> SECURESIGN-185 | Add tests to all pipelines

- .tekton/rekor-server-pull-request.yaml
Replacing the tags with the shas for the rekor-build-test-image and rekor-e2e-test tasks
> fix:fix EC for rekor-server

- docker-compose.yml
We are running Rekor end to end tests in Konflux testing our images and stack. This change to the docker compose file should only affect GitHub Actions e2e tests.
This partially reverts https://github.com/securesign/rekor/pull/159
//cc @Gregory-Pereira
> chore: use upstream redis for GitHub e2e tests

- policy-data/task-bundles.yaml
It is now possible to configure `ec` to accept one or more custom task bundles during a pipelinerun by specifying these bundles in our ec policy file. The addition of these task bundles to this repo will need to be followed by updates to EC policy used by Konflux.
> ec(task-bundles): add rekor test task bundles

- .gitignore
- Dockerfile.rekor-cli.rh
```
Go compliance shim [30169] [][]: final command line arguments: "build" "-o" "rekor_cli_windows_amd64.exe" "-trimpath" "-ldflags" "-X sigs.k8s.io/release-utils/version.gitVersion=1c1ec27 -X sigs.k8s.io/release-utils/version.gitCommit=1c1ec27231f216c4d5c09e3bf55f2d8c4dfe1c3d -X sigs.k8s.io/release-utils/version.gitTreeState=clean -X sigs.k8s.io/release-utils/version.buildDate=2024-10-02T07:38:26Z -w -s" "./cmd/rekor-cli" 
```
>  fix: Remove dirty tag from rekor-cli --version

- Dockerfile.backfill-redis.rh
Because of changes to how we will be storing indexes for backfill redis I need the redis cli, available from within the backfill-reds image
> Update base image for backfill-redis

- renovate.json
Konflux uses the inherited config approach which requires a repo within our org containing a specific config. Which has now been created.
> Removing Renovate as it is uneeded
